// Vuetify
import "vuetify/styles";
// import "@mdi/font/css/materialdesignicons.css";
import { createVuetify } from "vuetify";
import * as components from "vuetify/components";
import * as directives from "vuetify/directives";
import { aliases, mdi } from "vuetify/iconsets/mdi-svg";
import {
  mdiFilter,
  mdiFilterOutline,
  mdiReload,
  mdiMagnifyScan,
  mdiBackspaceOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiDomain,
  mdiAlphabeticalVariant,
  mdiCalendarMonthOutline,
  mdiChartPieOutline,
  mdiChartPie,
  mdiSelectMultiple,
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
  mdiCheckboxBlankOffOutline,
  mdiCheckboxMultipleMarked,
  mdiCheckboxMultipleBlankOutline,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLinkVariantPlus,
  mdiLinkVariantMinus,
  mdiDatabase,
  mdiDatabaseCheck,
  mdiDatabaseMinus,
  mdiDatabaseOff,
  mdiDatabaseEdit,
  mdiDatabaseRemove,
  mdiCloud,
  mdiCloudDownload,
  mdiCloudOff,
  mdiCloudAlert,
  mdiCloudCheckVariant,
  mdiGamepadSquare,
  mdiMicroSd,
  mdiAutorenew,
  mdiSyncOff,
  mdiDelete,
  mdiDeleteEmpty,
  mdiImage,
  mdiImageCheck,
  mdiImageMinus,
  mdiImageRemove,
  mdiFolderOpen,
  mdiFolderMove,
  mdiContentSave,
  mdiContentSaveMinus,
  mdiContentSaveOff,
  mdiSearchWeb,
  mdiMenuDown,
  mdiFingerprint,
  mdiTagMultiple,
  mdiStop,
  mdiSkipNext,
  mdiChevronLeft,
  mdiChevronRight,
  mdiMagnify,
  mdiPackageVariantClosed,
  mdiPackageVariant,
  mdiDownload,
  mdiFilePlus,
  mdiFileEdit,
  mdiFileRemove,
  mdiPencil,
  mdiPlusThick,
  mdiMinusThick,
  mdiUpdate,
  mdiArrowRightBold,
  mdiArrowLeftBold,
  mdiPageLast,
  mdiFolder,
  mdiFile,
  mdiDotsVertical,
  mdiCog,
  mdiFileSync,
  mdiArrowLeftRightBold,
  mdiMinusCircleOutline,
  mdiPlusCircleOutline,
  mdiCheckBold,
  mdiConsole,
  mdiPower,
  mdiCodeJson,
  mdiCloudOutline,
  mdiController,
  mdiWeb,
  mdiApplicationOutline,
  mdiSteam,
  mdiArrowUpRight,
  mdiArrowUpRightBold,
  mdiTranslate,
} from "@mdi/js";

import customWineEmpty from "./icons/customWineEmpty.vue";
import customWineEmptyVariant from "./icons/customWineEmptyVariant.vue";
import customWineHalf from "./icons/customWineHalf.vue";

const aliasesCustom = {
  ...aliases,
  customWineEmpty,
  customWineEmptyVariant,
  customWineHalf,
  mdiFilter,
  mdiFilterOutline,
  mdiReload,
  mdiMagnifyScan,
  mdiBackspaceOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiDomain,
  mdiAlphabeticalVariant,
  mdiCalendarMonthOutline,
  mdiChartPieOutline,
  mdiChartPie,
  mdiSelectMultiple,
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
  mdiCheckboxBlankOffOutline,
  mdiCheckboxMultipleMarked,
  mdiCheckboxMultipleBlankOutline,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLinkVariantPlus,
  mdiLinkVariantMinus,
  mdiDatabase,
  mdiDatabaseCheck,
  mdiDatabaseMinus,
  mdiDatabaseOff,
  mdiDatabaseEdit,
  mdiDatabaseRemove,
  mdiCloud,
  mdiCloudOutline,
  mdiCloudDownload,
  mdiCloudOff,
  mdiCloudAlert,
  mdiCloudCheckVariant,
  mdiGamepadSquare,
  mdiMicroSd,
  mdiAutorenew,
  mdiSyncOff,
  mdiDelete,
  mdiDeleteEmpty,
  mdiImage,
  mdiImageCheck,
  mdiImageMinus,
  mdiImageRemove,
  mdiFolder,
  mdiFolderOpen,
  mdiFolderMove,
  mdiFile,
  mdiContentSave,
  mdiContentSaveMinus,
  mdiContentSaveOff,
  mdiSearchWeb,
  mdiMenuDown,
  mdiFingerprint,
  mdiTagMultiple,
  mdiStop,
  mdiSkipNext,
  mdiChevronLeft,
  mdiChevronRight,
  mdiMagnify,
  mdiPackageVariantClosed,
  mdiPackageVariant,
  mdiDownload,
  mdiFilePlus,
  mdiFileEdit,
  mdiFileRemove,
  mdiPencil,
  mdiPlusThick,
  mdiMinusThick,
  mdiUpdate,
  mdiArrowRightBold,
  mdiArrowLeftBold,
  mdiPageLast,
  mdiDotsVertical,
  mdiCog,
  mdiFileSync,
  mdiArrowLeftRightBold,
  mdiMinusCircleOutline,
  mdiPlusCircleOutline,
  mdiCheckBold,
  mdiConsole,
  mdiPower,
  mdiCodeJson,
  mdiController,
  mdiWeb,
  mdiApplicationOutline,
  mdiSteam,
  mdiArrowUpRight,
  mdiArrowUpRightBold,
  mdiTranslate,
};

const vuetify = createVuetify({
  components,
  directives,
  icons: {
    defaultSet: "mdi",
    aliases: {
      ...aliasesCustom,
      // ...aliases,
      // account: mdiAccount,
      // customWineEmpty: customWineEmpty,
      // customWineFill: customWineFill,
    },
    sets: {
      mdi,
    },
  },
});

export default vuetify;
