// Vuetify
import "vuetify/styles";
// import "@mdi/font/css/materialdesignicons.css";
import { createVuetify } from "vuetify";
import * as components from "vuetify/components";
import * as directives from "vuetify/directives";
import { aliases, mdi } from "vuetify/iconsets/mdi-svg";
import {
  mdiFilter,
  mdiFilterOutline,
  mdiReload,
  mdiMagnifyScan,
  mdiBackspaceOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiDomain,
  mdiAlphabeticalVariant,
  mdiCalendarMonthOutline,
  mdiChartPieOutline,
  mdiSelectMultiple,
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
  mdiCheckboxBlankOffOutline,
  mdiCheckboxMultipleMarked,
  mdiCheckboxMultipleBlankOutline,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLinkVariantPlus,
  mdiLinkVariantMinus,
  mdiDatabase,
  mdiDatabaseCheck,
  mdiDatabaseMinus,
  mdiDatabaseOff,
  mdiDatabaseEdit,
  mdiDatabaseRemove,
  mdiCloud,
  mdiCloudDownload,
  mdiCloudOff,
  mdiCloudCheckVariant,
  mdiGamepadSquare,
  mdiMicroSd,
  mdiSync,
  mdiSyncOff,
  mdiDelete,
  mdiDeleteEmpty,
  mdiImage,
  mdiImageCheck,
  mdiImageMinus,
  mdiImageRemove,
  mdiFolderOpen,
  mdiFolderMove,
  mdiContentSaveMinus,
  mdiContentSaveOff,
  mdiIdeogramCjkVariant,
  mdiSearchWeb,
  mdiMenuDown,
  mdiFingerprint,
  mdiTagMultiple,
  mdiStop,
  mdiSkipNext,
  mdiChevronLeft,
  mdiChevronRight,
  mdiMagnify,
  mdiPackageVariantClosed,
  mdiPackageVariant,
} from "@mdi/js";

import customWineEmpty from "./icons/customWineEmpty.vue";
import customWineHalf from "./icons/customWineHalf.vue";

const aliasesCustom = {
  ...aliases,
  customWineEmpty,
  customWineHalf,
  mdiFilter,
  mdiFilterOutline,
  mdiReload,
  mdiMagnifyScan,
  mdiBackspaceOutline,
  mdiSortAscending,
  mdiSortDescending,
  mdiDomain,
  mdiAlphabeticalVariant,
  mdiCalendarMonthOutline,
  mdiChartPieOutline,
  mdiSelectMultiple,
  mdiCheckboxMarked,
  mdiCheckboxBlankOutline,
  mdiCheckboxBlankOffOutline,
  mdiCheckboxMultipleMarked,
  mdiCheckboxMultipleBlankOutline,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLinkVariantPlus,
  mdiLinkVariantMinus,
  mdiDatabase,
  mdiDatabaseCheck,
  mdiDatabaseMinus,
  mdiDatabaseOff,
  mdiDatabaseEdit,
  mdiDatabaseRemove,
  mdiCloud,
  mdiCloudDownload,
  mdiCloudOff,
  mdiCloudCheckVariant,
  mdiGamepadSquare,
  mdiMicroSd,
  mdiSync,
  mdiSyncOff,
  mdiDelete,
  mdiDeleteEmpty,
  mdiImage,
  mdiImageCheck,
  mdiImageMinus,
  mdiImageRemove,
  mdiFolderOpen,
  mdiFolderMove,
  mdiContentSaveMinus,
  mdiContentSaveOff,
  mdiIdeogramCjkVariant,
  mdiSearchWeb,
  mdiMenuDown,
  mdiFingerprint,
  mdiTagMultiple,
  mdiStop,
  mdiSkipNext,
  mdiChevronLeft,
  mdiChevronRight,
  mdiMagnify,
  mdiPackageVariantClosed,
  mdiPackageVariant,
};

const vuetify = createVuetify({
  components,
  directives,
  icons: {
    defaultSet: "mdi",
    aliases: {
      ...aliasesCustom,
      // ...aliases,
      // account: mdiAccount,
      // customWineEmpty: customWineEmpty,
      // customWineFill: customWineFill,
    },
    sets: {
      mdi,
    },
  },
});

export default vuetify;
